In [1]:
import numpy as np

def gaussElimin(a,b):
    n = len(b)

    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a [i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam * a[k,k+1:n]
                b[i] = b[i] - lam*b[k]

    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]

    return b
    

In [2]:
A = np.array([[2, 1, 4],[4, 11, -1], [8, -3, 2]])
B = np.array([12, 33, 20])

print(A)
print('\n')
print(B)
print('\n')

#Calling gaussElimin function...
gaussElimin(A,B)

[[ 2  1  4]
 [ 4 11 -1]
 [ 8 -3  2]]


[12 33 20]




array([3, 2, 1])